## 1. 와인종류분류

In [ ]:
import pandas as pd
import numpy as np

###############  실기환경 복사 영역  ###############
import pandas as pd
import numpy as np
# 실기 시험 데이터셋으로 셋팅하기 (수정금지)

from sklearn.datasets import load_wine
# 와인 데이터셋을 로드합니다.
wine = load_wine()
x = pd.DataFrame(wine.data, columns=wine.feature_names)
y = pd.DataFrame(wine.target)

# 실기 시험 데이터셋으로 셋팅하기 (수정금지)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,
                                                    stratify=y,
                                                    random_state=2023)

x_test = pd.DataFrame(x_test)
x_train = pd.DataFrame(x_train)
y_train = pd.DataFrame(y_train)

x_test.reset_index()
y_train.columns = ['target']
###############  실기환경 복사 영역  ###############

#### 와인의 종류를 분류해보자. <br/> - 데이터의 결측치, 이상치에 대해 처리하고 <br/> - 분류모델을 사용하여 정확도, F1 score, AUC 값을 산출하시오. <br/> - 제출은 result 변수에 담아 양식에 맞게 제출하시오. <br/> ex) 양식 예시: pd.DataFrame({'result': y_result }).to_csv('수험번호.csv, index=False)

In [ ]:
# 데이터 확인(EDA)
x_train.head(5)
x_test.head(5)
y_train.head(5)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)

# 데이터 결측치, 이상치
x_train.info() # 결측치 X
y_train.info() # 결측치 X

x_train.describe() # 이상치 X

y_train.value_counts() # 3개 분류

(142, 13)
(142, 1)
(36, 13)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 142 entries, 52 to 115
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       142 non-null    float64
 1   malic_acid                    142 non-null    float64
 2   ash                           142 non-null    float64
 3   alcalinity_of_ash             142 non-null    float64
 4   magnesium                     142 non-null    float64
 5   total_phenols                 142 non-null    float64
 6   flavanoids                    142 non-null    float64
 7   nonflavanoid_phenols          142 non-null    float64
 8   proanthocyanins               142 non-null    float64
 9   color_intensity               142 non-null    float64
 10  hue                           142 non-null    float64
 11  od280/od315_of_diluted_wines  142 non-null    float64
 12  proline                       142 n

target
1         57
0         47
2         38
dtype: int64

In [ ]:
# 데이터 분류
from sklearn.model_selection import train_test_split

X_train, x_val, Y_train, y_val = train_test_split(
    x_train,
    y_train['target'],
    random_state=2023,
    stratify=y_train['target'],
    test_size=0.2
)

print(X_train.shape)
print(Y_train.shape)
print(x_val.shape)
print(y_val.shape)

(113, 13)
(113,)
(29, 13)
(29,)


In [ ]:
# 모델 만들고 실행
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, Y_train)

y_pred = model.predict(x_val)

import sklearn.metrics as mc
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

acc = accuracy_score(y_val, y_pred)
f1 = f1_score(y_val, y_pred, average='macro')

# 정확도
print(acc)

# f1
print(f1)

y_result = model.predict(x_test)
result = model.predict_proba(x_test)

print(y_result)
print(result)

pd.DataFrame({'result': y_result }).to_csv('수험번호.csv', index=False)
# check = pd.read_csv('수험번호.csv')
# print(check)

1.0
1.0
[2 2 2 0 1 1 1 0 2 1 2 0 2 1 1 1 1 2 1 0 1 0 1 0 0 1 0 2 1 1 1 2 0 0 2 0]
[[0.01 0.   0.99]
 [0.11 0.09 0.8 ]
 [0.   0.13 0.87]
 [0.98 0.02 0.  ]
 [0.05 0.92 0.03]
 [0.46 0.49 0.05]
 [0.   0.77 0.23]
 [0.84 0.14 0.02]
 [0.04 0.26 0.7 ]
 [0.   1.   0.  ]
 [0.04 0.03 0.93]
 [0.91 0.03 0.06]
 [0.04 0.07 0.89]
 [0.04 0.96 0.  ]
 [0.   0.82 0.18]
 [0.25 0.71 0.04]
 [0.   0.94 0.06]
 [0.   0.02 0.98]
 [0.01 0.98 0.01]
 [0.69 0.3  0.01]
 [0.   0.95 0.05]
 [0.93 0.06 0.01]
 [0.   0.96 0.04]
 [0.95 0.05 0.  ]
 [0.8  0.2  0.  ]
 [0.   0.94 0.06]
 [0.79 0.2  0.01]
 [0.   0.09 0.91]
 [0.   0.98 0.02]
 [0.21 0.77 0.02]
 [0.23 0.77 0.  ]
 [0.05 0.09 0.86]
 [0.97 0.01 0.02]
 [0.95 0.05 0.  ]
 [0.   0.02 0.98]
 [0.94 0.03 0.03]]




---



### 2. 붓꽃 분류

In [ ]:
###############  실기환경 복사 영역  ###############
import pandas as pd
import numpy as np
# 실기 시험 데이터셋으로 셋팅하기 (수정금지)
from sklearn.datasets import load_iris
# Iris 데이터셋을 로드
iris = load_iris()
x = pd.DataFrame(iris.data, columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
y = iris.target   # 'setosa'=0, 'versicolor'=1, 'virginica'=2
y = np.where(y>0, 1, 0) # setosa 종은 0, 나머지 종은 1로 변경

# 실기 시험 데이터셋으로 셋팅하기 (수정금지)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,
                                                    stratify=y,
                                                    random_state=2023)

x_test = pd.DataFrame(x_test)
x_train = pd.DataFrame(x_train)
y_train = pd.DataFrame(y_train)
y_train.columns = ['species']

# 결측치 삽입
x_test['sepal_length'].iloc[0] = None
x_train['sepal_length'].iloc[0] = None
# 이상치 삽입
x_train['sepal_width'].iloc[0] = 150
###############  실기환경 복사 영역  ###############

#### 붓꽃의 종을 분류해보자. <br/> - 데이터의 결측치, 이상치에 대해 처리하고 <br/> - 분류모델을 사용하여 정확도, F1 score, AUC값을 산출하시오. <br/> - 제출은 result 변수에 담아 양식에 맞게 제출하시오. <br/> ex) 양식 예시: pd.DataFrame({'result': y_result }).to_csv('수험번호.csv, index=False)

In [ ]:
# 데이터 탐색 (EDA)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)

x_train.info() # sepal_length 결측치 존재
y_train.info()
print(y_train.value_counts())

# 결측치 채우기 (연속형이므로 중앙값으로)
median = x_train['sepal_length'].median()
x_train['sepal_length'] = x_train['sepal_length'].fillna(median)
x_test['sepal_length'] = x_test['sepal_length'].fillna(median)

# 이상치 확인
x_train.describe() # sepal_width의 max가 상당히 크다
# x_train.head(10)

Q3 = x_train['sepal_width'].quantile(0.75)
Q1 = x_train['sepal_width'].quantile(0.25)
IQR = Q3 - Q1

max_outlier = Q3 + (IQR * 1.5)
x_train_outlier = x_train[x_train['sepal_width'] > max_outlier]

# 이상치 대체
x_train['sepal_width'] = np.where(x_train['sepal_width'] > 10, x_train['sepal_width'].median(), x_train['sepal_width'])
x_train

x_train.describe()
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)

(120, 4)
(120, 1)
(30, 4)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 120 entries, 2 to 44
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  120 non-null    float64
 1   sepal_width   120 non-null    float64
 2   petal_length  120 non-null    float64
 3   petal_width   120 non-null    float64
dtypes: float64(4)
memory usage: 4.7 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   species  120 non-null    int64
dtypes: int64(1)
memory usage: 1.1 KB
species
1          80
0          40
dtype: int64
(120, 4)
(120, 1)
(30, 4)


In [ ]:
# 데이터 분류
from sklearn.model_selection import train_test_split
X_train, x_val, Y_train, y_val = train_test_split(
    x_train,
    y_train['species'],
    random_state = 2023,
    test_size=0.2,
    stratify=y_train['species']
)

# 모델 생성
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, Y_train)

# 예측
y_pred = model.predict(x_val)

# 정확도 출력
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

acc = accuracy_score(y_val, y_pred)
acc

f1 = f1_score(y_val, y_pred)
f1

roc = roc_auc_score(y_val, y_pred)
roc

1.0

In [ ]:
# x_test에 넣기: 예측
y_result = model.predict(x_test)
y_result_prob = model.predict_proba(x_test)
y_result_prob

array([[0.  , 1.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.05, 0.95],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.05, 0.95],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.09, 0.91],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.01, 0.99],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.02, 0.98],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.  , 1.  ]])

In [ ]:
pd.DataFrame({'result': y_result }).to_csv('수험번호.csv', index=False)
# check = pd.read_csv('수험번호.csv')
# print(check)



---



###3. 타이타닉 생존자 분류

In [ ]:
###############  복사 영역  ###############
# 실기 시험 데이터셋으로 셋팅하기 (수정금지)

# Seaborn의 내장 타이타닉 데이터셋을 불러옵니다.
import seaborn as sns
df = sns.load_dataset('titanic')

x = df.drop('survived', axis=1)
y = df['survived']

# 실기 시험 데이터셋으로 셋팅하기 (수정금지)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,
                                                    stratify=y,
                                                    random_state=2023)

x_test = pd.DataFrame(x_test)
x_train = pd.DataFrame(x_train)
y_train = pd.DataFrame(y_train)
y_test = pd.DataFrame(y_test) # 평가용

x_test.reset_index()
y_train.columns = ['target']
y_test.columns = ['target']
###############  복사 영역  ###############

#### 타이타닉 생존자 예측 문제 <br/> - 데이터의 결측치, 이상치에 대해 처리하고 <br/> - 분류모델을 사용하여 정확도, F1 score, AUC값을 산출하시오. <br/> - 제출은 result 변수에 담아 양식에 맞게 제출하시오. <br/> ex) 양식 예시: pd.DataFrame({'result': y_result }).to_csv('수험번호.csv, index=False)

In [ ]:
# 데이터 확인하기
# x_test.info()

# 결측치 존재: deck는 결측치가 너무 많음
# 중복 데이터 존재: alive, class, who, embarked_town
x_test = x_test.drop(columns=['deck','alive','class','who','embark_town'])
x_train = x_train.drop(columns=['deck','alive','class','who','embark_town'])

In [ ]:
# 결측치 확인 후 median 값으로 변경
x_test.isnull().sum()
age_median = x_test['age'].median()

x_train['age'] = x_train['age'].fillna(age_median)
x_test['age'] = x_test['age'].fillna(age_median)

# 범주형데이터 더미변수로 변경
x_test = pd.get_dummies(x_test)
x_train = pd.get_dummies(x_train)

In [ ]:
from sklearn.model_selection import train_test_split

X_TRAIN, x_val, Y_TRAIN, y_val = train_test_split(
    x_train,
    y_train['target'],
    test_size=0.2,
    random_state=2023,
    stratify=y_train['target']
)

In [ ]:
# 모델링
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_TRAIN, Y_TRAIN)

# 예측
y_pred = model.predict(x_val)

# 정확도 테스트
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix

acc = accuracy_score(y_val, y_pred)
print('acc', acc)

f1 = f1_score(y_val, y_pred)
print('f1',f1)

roc = roc_auc_score(y_val, y_pred)
print('roc',roc)

cm = confusion_matrix(y_val, y_pred)
cm

acc 0.8391608391608392
f1 0.7889908256880734
roc 0.8284090909090909


array([[77, 11],
       [12, 43]])

In [ ]:
# x-test에 적용
y_result = model.predict(x_test)
pd.DataFrame({'result': y_result }).to_csv('수험번호.csv', index=False)
# check = pd.read_csv('수험번호.csv')
# print(check)

from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix
acc_pred_f = accuracy_score(y_test, y_result)
acc_pred_f

f1_pred_f = f1_score(y_test, y_result)
f1_pred_f

roc_pred_f = roc_auc_score(y_test, y_result)
roc_pred_f

0.7587615283267457



---



### 4. 당뇨진척정도 (회귀)

In [ ]:
###############  실기환경 복사 영역  ###############
import pandas as pd
import numpy as np
# 실기 시험 데이터셋으로 셋팅하기 (수정금지)
from sklearn.datasets import load_diabetes
# diabetes 데이터셋 로드
diabetes = load_diabetes()
x = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
y = pd.DataFrame(diabetes.target)

# 실기 시험 데이터셋으로 셋팅하기 (수정금지)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,
                                                    random_state=2023)

x_test = pd.DataFrame(x_test.reset_index())
x_train = pd.DataFrame(x_train.reset_index())
y_train = pd.DataFrame(y_train.reset_index())

x_test.rename(columns={'index':'cust_id'}, inplace=True)
x_train.rename(columns={'index':'cust_id'}, inplace=True)
y_train.columns = ['cust_id', 'target']
###############  실기환경 복사 영역  ###############

#### 당뇨병 환자의 질병 진행정도를 예측해보자. <br/> - 데이터의 결측치, 이상치에 대해 처리하고 <br/> - 회귀모델을 사용하여 Rsq, MSE 값을 산출하시오. <br/> - 제출은 cust_id, target 변수를 가진 dataframe 형태로 제출하시오.

In [ ]:
# 데이터탐색(EDA)
# x_test.info()
# x_train.info()
# y_train.info()

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
y_train.head(5) #cust_id, target존재 -> cust_id는 불필요하므로 카피 떠놓고 제거

# 결측치 확인 : 없음
# print(x_train.isnull().sum())
# print(x_test.isnull().sum())
# print(y_train.isnull().sum())

# 이상치 확인
# x_train.describe()

cust_id = x_test['cust_id'].copy()

x_train = x_train.drop(columns=['cust_id'])
x_test = x_test.drop(columns=['cust_id'])

(353, 11)
(89, 11)
(353, 2)


In [ ]:
# 데이터 나누기
from sklearn.model_selection import train_test_split

X_TRAIN, x_val, Y_TRAIN, y_val = train_test_split(
    x_train,
    y_train['target'],
    random_state=66,
    test_size=0.2
)

In [ ]:
# 모델링
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(random_state=2023)
model.fit(X_TRAIN, Y_TRAIN)

y_pred = model.predict(x_val)

# 정확도 테스트
from sklearn.metrics import r2_score, mean_squared_error

r2 = r2_score(y_val, y_pred)
print('r2',r2)

mse = mean_squared_error(y_val, y_pred)
print('mse',mse)

r2 0.5445622216838756
mse 2938.386609859155


In [ ]:
y_result = model.predict(x_test)
result = pd.DataFrame({
    'cust_id': cust_id,
    'target': y_result
})
result

pd.DataFrame({'result': y_result}).to_csv('수험번호.csv', index=False)
# check = pd.read_csv('수험번호.csv')
# print(check)

cust_id  target
0       280  185.92
1       412  216.96
2        68   82.22
3       324  179.69
4       101   90.62
..      ...     ...
84       80  182.40
85      395  171.05
86      331   99.82
87      361  104.98
88      257  129.04

[89 rows x 2 columns]



---



### 5. 팁 예측하기 (회귀)

In [ ]:
###############  복사 영역  ###############
# 실기 시험 데이터셋으로 셋팅하기 (수정금지)

import seaborn as sns
# tips 데이터셋 로드
df = sns.load_dataset('tips')

x = df.drop(['tip'], axis=1)
y = df['tip']


# 실기 시험 데이터셋으로 셋팅하기 (수정금지)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2023)

x_test = pd.DataFrame(x_test.reset_index())
x_train = pd.DataFrame(x_train.reset_index())
y_train = pd.DataFrame(y_train.reset_index())

x_test.rename(columns={'index':'cust_id'}, inplace=True)
x_train.rename(columns={'index':'cust_id'}, inplace=True)
y_train.columns = ['cust_id', 'target']

#### 레스토랑의 tip 예측 문제 <br/> - 데이터의 결측치, 이상치, 변수에 대해 처리하고 <br/> - 회귀모델을 사용하여 Rsq, MSE 값을 산출하시오.

In [ ]:
x_train.info() #범주형 처리 필요
x_test.info()
y_train.info() #cust_id, target 존재
x_train.describe(include='category')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   cust_id     195 non-null    int64   
 1   total_bill  195 non-null    float64 
 2   sex         195 non-null    category
 3   smoker      195 non-null    category
 4   day         195 non-null    category
 5   time        195 non-null    category
 6   size        195 non-null    int64   
dtypes: category(4), float64(1), int64(2)
memory usage: 6.0 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   cust_id     49 non-null     int64   
 1   total_bill  49 non-null     float64 
 2   sex         49 non-null     category
 3   smoker      49 non-null     category
 4   day         49 non-null     category
 5   time        49 non-null     category
 6   size        

sex smoker  day    time
count    195    195  195     195
unique     2      2    4       2
top     Male     No  Sat  Dinner
freq     125    120   71     142

In [ ]:
# cust_id 삭제하고 혹시모르니 복제뜨기
cust_id = x_test['cust_id'].copy()

x_test = x_test.drop(columns=['cust_id'])
x_train = x_train.drop(columns=['cust_id'])

# 범주형 처리
x_train = pd.get_dummies(x_train)
x_test = pd.get_dummies(x_test)

In [ ]:
# 결측치 처리
print(x_train.isnull().sum())
print(x_test.isnull().sum())
print(y_train.isnull().sum())

total_bill     0
size           0
sex_Male       0
sex_Female     0
smoker_Yes     0
smoker_No      0
day_Thur       0
day_Fri        0
day_Sat        0
day_Sun        0
time_Lunch     0
time_Dinner    0
dtype: int64
total_bill     0
size           0
sex_Male       0
sex_Female     0
smoker_Yes     0
smoker_No      0
day_Thur       0
day_Fri        0
day_Sat        0
day_Sun        0
time_Lunch     0
time_Dinner    0
dtype: int64
cust_id    0
target     0
dtype: int64


In [ ]:
# 데이터 분리
from sklearn.model_selection import train_test_split

X_TRAIN, x_val, Y_TRAIN, y_val = train_test_split(
    x_train,
    y_train['target'],
    random_state = 23,
    test_size = 0.2
)

In [ ]:
# 모델 생성
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error

model = RandomForestRegressor(random_state=2023)
model.fit(X_TRAIN, Y_TRAIN)

# 예측하기
y_pred = model.predict(x_val)

# 정확도 확인
r2 = r2_score(y_val, y_pred) # 1에 가까울수록 좋음
mse = mean_squared_error(y_val, y_pred)

print('mse', mse)
print('rmse', mse**0.5)
print('r2', r2)

# x_test 진행
y_result = model.predict(x_test)
result = pd.DataFrame({'cust_id': cust_id, 'target': y_result})

# 저장
pd.DataFrame({'result': y_result}).to_csv('수험번호.csv', index=False)
# check = pd.read_csv('수험번호.csv')
# print(check.head())

mse 0.9812277338461534
rmse 0.990569398803614
r2 0.4286497615634072
